dist: trusty
sudo: false
language: python
python:
  - "3.6"
cache: pip
before_install:
  - export TZ=America/New_York
install:
  - pip install --requirement requirements.txt
script:
  - pytest
after_success:
  - test $TRAVIS_EVENT_TYPE = "cron" &&
    python upkeep.py --token=$GH_TOKEN
