name: run_upkeep

on:
  push:
  schedule:
    - cron: "0 15 * * *"

jobs:
  run_upkeep:
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    env:
      TZ: America/New_York
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
            python-version: 3.10.5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Upkeep
        run: python upkeep.py --token=${{ secrets.GITHUB_TOKEN }} --workdays-ahead=1
