name: run_tests

on: push

jobs:
  run_tests:
    env:
      TZ: America/New_York
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with: 
          python-version: 3.10.5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
